export const FETCH_CURRENCIES = 'FETCH_CURRENCIES';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const FETCH_CURRENCIES_ERROR = 'FETCH_CURRENCIES_ERROR';

export const ON_CHANGE_INPUT1 = 'ON_CHANGE_INPUT1';
export const ON_CHANGE_INPUT2 = 'ON_CHANGE_INPUT2';

export const ON_CHANGE_CURRENT_CURRENCY1 = 'ON_CHANGE_CURRENT_CURRENCY1';
export const ON_CHANGE_CURRENT_CURRENCY2 = 'ON_CHANGE_CURRENT_CURRENCY2';

export const FETCH_NBU_CURRENCIES = 'FETCH_NBU_CURRENCIES';
export const FETCH_NBU_CURRENCIES_ERROR = 'FETCH_NBU_CURRENCIES_ERROR';

export const FETCH_FINANCIAL_NEWS = 'FETCH_FINANCIAL_NEWS';
export const FETCH_FINANCIAL_NEWS_ERROR = 'FETCH_FINANCIAL_NEWS_ERROR';
